; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Barrien notify"
#define MyAppVersion "5.1"
#define MyAppPublisher "dindjulinar"
#define MyAppURL "https://sites.google.com/view/media-dindju"
#define MyAppExeName "Dindju BARRIEN Notify.exe"
#expr EmitLanguagesSection

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9F39B99E-01BF-44E0-90BF-B12C93EDCCA0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=Barrien notify setup 5.1
SolidCompression=yes
WizardStyle=classic dynamic

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\mathis.dame\Desktop\dindju-notify-5.0.0\Dindju-Notify-5\dindju notify\bin\Debug\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mathis.dame\Desktop\dindju-notify-5.0.0\Dindju-Notify-5\dindju notify\bin\Debug\Dindju BARRIEN Notify.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mathis.dame\Desktop\dindju-notify-5.0.0\Dindju-Notify-5\dindju notify\bin\Debug\Dindju BARRIEN Notify.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mathis.dame\Desktop\dindju-notify-5.0.0\Dindju-Notify-5\dindju notify\bin\Debug\Dindju BARRIEN Notify.xml"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

